ALTER TABLE person ADD CONSTRAINT unique_email UNIQUE (email);
ALTER TABLE person ALTER COLUMN name SET NOT NULL;
ALTER TABLE person ALTER COLUMN email SET NOT NULL;
ALTER TABLE person ALTER COLUMN password SET NOT NULL;

ALTER TABLE dishes ALTER COLUMN name SET NOT NULL;
ALTER TABLE dishes ALTER COLUMN price SET NOT NULL;

ALTER TABLE restaurant ALTER COLUMN name SET NOT NULL;
ALTER TABLE restaurant ALTER COLUMN address SET NOT NULL;

ALTER TABLE roles ALTER COLUMN role SET NOT NULL;

ALTER TABLE sessions ALTER COLUMN email SET NOT NULL;
ALTER TABLE sessions ALTER COLUMN expiry SET NOT NULL;
